const Data = [
  {
    "id": "63",
    "category": "Brown Rice ",
    "name": "Teriyaki Chicken ",
    "description": "Teriyaki Chicken ",
    "kJs": "735kJ",
    "Wheat": "",
    "Gluten": "",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "",
    "Milk": "",
    "Fish": "",
    "Peanut": "",
    "Soy": "YES",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "427",
    "category": "Brown Rice ",
    "name": "Spicy Salmon & Cucumber ",
    "description": "",
    "kJs": "774kJ",
    "Wheat": "",
    "Gluten": "",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "YES",
    "Milk": "",
    "Fish": "YES",
    "Peanut": "",
    "Soy": "",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "800",
    "category": "Brown Rice ",
    "name": "Salt & Pepper Squid ",
    "description": "",
    "kJs": "906kJ",
    "Wheat": "YES",
    "Gluten": "YES",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "YES",
    "Milk": "",
    "Fish": "YES",
    "Peanut": "",
    "Soy": "",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "831",
    "category": "Brown Rice ",
    "name": "Cooked Tuna & Avocado ",
    "description": "Cooked Tuna & Avocado ",
    "kJs": "808kJ",
    "Wheat": "",
    "Gluten": "",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "YES",
    "Milk": "",
    "Fish": "YES",
    "Peanut": "",
    "Soy": "YES",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "832",
    "category": "Brown Rice ",
    "name": "Crispy Chicken ",
    "description": "Crispy Chicken ",
    "kJs": "901kJ",
    "Wheat": "YES",
    "Gluten": "YES",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "YES",
    "Milk": "",
    "Fish": "",
    "Peanut": "",
    "Soy": "YES",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "833",
    "category": "Brown Rice ",
    "name": "Smoked Salmon & Avocado ",
    "description": "",
    "kJs": "909kJ",
    "Wheat": "",
    "Gluten": "",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "YES",
    "Milk": "",
    "Fish": "YES",
    "Peanut": "",
    "Soy": "",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "834",
    "category": "Brown Rice ",
    "name": "Salmon & Avocado ",
    "description": "Salmon & Avocado ",
    "kJs": "905kJ",
    "Wheat": "",
    "Gluten": "",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "YES",
    "Milk": "",
    "Fish": "YES",
    "Peanut": "",
    "Soy": "",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "836",
    "category": "Brown Rice ",
    "name": "Prawn & Avocado",
    "description": "Prawn & Avocado",
    "kJs": "777kJ",
    "Wheat": "",
    "Gluten": "",
    "Crustacea": "YES",
    "Mollusc": "",
    "Egg": "YES",
    "Milk": "",
    "Fish": "",
    "Peanut": "",
    "Soy": "",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "837",
    "category": "Brown Rice ",
    "name": "California ",
    "description": "",
    "kJs": "825kJ",
    "Wheat": "YES",
    "Gluten": "YES",
    "Crustacea": "YES",
    "Mollusc": "",
    "Egg": "YES",
    "Milk": "",
    "Fish": "YES",
    "Peanut": "",
    "Soy": "YES",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "839",
    "category": "Brown Rice ",
    "name": "Spicy Cooked Tuna & Cucumber",
    "description": "Spicy Cooked Tuna & Cucumber",
    "kJs": "871kJ",
    "Wheat": "",
    "Gluten": "",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "YES",
    "Milk": "",
    "Fish": "YES",
    "Peanut": "",
    "Soy": "YES",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "841",
    "category": "Brown Rice ",
    "name": "Panko Prawn ",
    "description": "",
    "kJs": "1020kJ",
    "Wheat": "YES",
    "Gluten": "YES",
    "Crustacea": "YES",
    "Mollusc": "",
    "Egg": "YES",
    "Milk": "",
    "Fish": "",
    "Peanut": "",
    "Soy": "YES",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "842",
    "category": "Brown Rice ",
    "name": "Tempura Salmon",
    "description": "",
    "kJs": "1010kJ",
    "Wheat": "YES",
    "Gluten": "YES",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "YES",
    "Milk": "",
    "Fish": "YES",
    "Peanut": "",
    "Soy": "YES",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "844",
    "category": "Brown Rice ",
    "name": "Tamago & Cucumber ",
    "description": "",
    "kJs": "682kJ",
    "Wheat": "",
    "Gluten": "",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "YES",
    "Milk": "YES",
    "Fish": "",
    "Peanut": "",
    "Soy": "",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "846",
    "category": "Brown Rice ",
    "name": "Vegetarian",
    "description": "Vegetarian",
    "kJs": "668kJ",
    "Wheat": "",
    "Gluten": "",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "",
    "Milk": "",
    "Fish": "",
    "Peanut": "",
    "Soy": "YES",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "YES",
    "Lupin": ""
  },
  {
    "id": "847",
    "category": "Brown Rice ",
    "name": "Cucumber & Avocado ",
    "description": "Cucumber & Avocado ",
    "kJs": "682kJ",
    "Wheat": "",
    "Gluten": "",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "",
    "Milk": "",
    "Fish": "",
    "Peanut": "",
    "Soy": "",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "853",
    "category": "Brown Rice ",
    "name": "Special California",
    "description": "Special California",
    "kJs": "668kJ",
    "Wheat": "YES",
    "Gluten": "YES",
    "Crustacea": "YES",
    "Mollusc": "",
    "Egg": "YES",
    "Milk": "",
    "Fish": "YES",
    "Peanut": "",
    "Soy": "YES",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "856",
    "category": "Brown Rice ",
    "name": "Peking Duck",
    "description": "",
    "kJs": "722kJ",
    "Wheat": "YES",
    "Gluten": "YES",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "",
    "Milk": "",
    "Fish": "",
    "Peanut": "",
    "Soy": "YES",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "858",
    "category": "Brown Rice ",
    "name": "Avocado ",
    "description": "Avocado ",
    "kJs": "722kJ",
    "Wheat": "",
    "Gluten": "",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "",
    "Milk": "",
    "Fish": "",
    "Peanut": "",
    "Soy": "",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "860",
    "category": "Brown Rice ",
    "name": "Tofu & Cucumber ",
    "description": "",
    "kJs": "741kJ",
    "Wheat": "",
    "Gluten": "",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "",
    "Milk": "",
    "Fish": "",
    "Peanut": "",
    "Soy": "YES",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "862",
    "category": "Brown Rice ",
    "name": "Cooked Tuna & Cucumber ",
    "description": "",
    "kJs": "841kJ",
    "Wheat": "",
    "Gluten": "",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "YES",
    "Milk": "",
    "Fish": "YES",
    "Peanut": "",
    "Soy": "YES",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "865",
    "category": "Brown Rice ",
    "name": "Spicy Prawn",
    "description": "",
    "kJs": "735kJ",
    "Wheat": "",
    "Gluten": "",
    "Crustacea": "YES",
    "Mollusc": "",
    "Egg": "YES",
    "Milk": "",
    "Fish": "",
    "Peanut": "",
    "Soy": "",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "TBC",
    "category": "Cabinet 3 . 0",
    "name": "Sushi Tacos ",
    "description": "",
    "kJs": "",
    "Wheat": "",
    "Gluten": "",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "",
    "Milk": "",
    "Fish": "",
    "Peanut": "",
    "Soy": "",
    "Sesame": "",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "TBC",
    "category": "Cabinet 3 . 0",
    "name": "Temaki ",
    "description": "",
    "kJs": "",
    "Wheat": "",
    "Gluten": "",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "",
    "Milk": "",
    "Fish": "",
    "Peanut": "",
    "Soy": "",
    "Sesame": "",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "TBC",
    "category": "Cabinet 3 . 0",
    "name": "Omu Sando ",
    "description": "",
    "kJs": "",
    "Wheat": "",
    "Gluten": "",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "",
    "Milk": "",
    "Fish": "",
    "Peanut": "",
    "Soy": "",
    "Sesame": "",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "315",
    "category": "Deluxe",
    "name": "Plain Inari",
    "description": "Plain Inari",
    "kJs": "302kJ",
    "Wheat": "",
    "Gluten": "",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "",
    "Milk": "",
    "Fish": "",
    "Peanut": "",
    "Soy": "YES",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "317",
    "category": "Deluxe",
    "name": "Seafood Inari",
    "description": "Seafood Inari",
    "kJs": "525kJ",
    "Wheat": "YES",
    "Gluten": "YES",
    "Crustacea": "YES",
    "Mollusc": "",
    "Egg": "YES",
    "Milk": "",
    "Fish": "YES",
    "Peanut": "",
    "Soy": "YES",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "318",
    "category": "Deluxe",
    "name": "Seaweed Inari",
    "description": "Seaweed Inari",
    "kJs": "531kJ",
    "Wheat": "YES",
    "Gluten": "YES",
    "Crustacea": "",
    "Mollusc": "YES",
    "Egg": "",
    "Milk": "",
    "Fish": "",
    "Peanut": "",
    "Soy": "YES",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "513",
    "category": "Deluxe",
    "name": "Pickled Squid Inari",
    "description": "Pickled Squid Inari",
    "kJs": "611kJ",
    "Wheat": "YES",
    "Gluten": "YES",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "",
    "Milk": "",
    "Fish": "YES",
    "Peanut": "",
    "Soy": "YES",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "550",
    "category": "Deluxe",
    "name": "Salmon Nigiri",
    "description": "Salmon Nigiri",
    "kJs": "236kJ",
    "Wheat": "",
    "Gluten": "",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "",
    "Milk": "",
    "Fish": "YES",
    "Peanut": "",
    "Soy": "",
    "Sesame": "",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "552",
    "category": "Deluxe",
    "name": "Fresh Tuna Nigiri",
    "description": "Fresh Tuna Nigiri",
    "kJs": "174kJ",
    "Wheat": "",
    "Gluten": "",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "",
    "Milk": "",
    "Fish": "YES",
    "Peanut": "",
    "Soy": "",
    "Sesame": "",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "1300",
    "category": "Deluxe",
    "name": "Prawn Nigiri",
    "description": "",
    "kJs": "140kJ",
    "Wheat": "",
    "Gluten": "",
    "Crustacea": "YES",
    "Mollusc": "",
    "Egg": "",
    "Milk": "",
    "Fish": "",
    "Peanut": "",
    "Soy": "",
    "Sesame": "",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "566",
    "category": "Deluxe",
    "name": "Prawn & Avocado Nigiri",
    "description": "Prawn & Avocado Nigiri",
    "kJs": "151kJ",
    "Wheat": "",
    "Gluten": "",
    "Crustacea": "YES",
    "Mollusc": "",
    "Egg": "",
    "Milk": "",
    "Fish": "",
    "Peanut": "",
    "Soy": "",
    "Sesame": "",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "599",
    "category": "Deluxe",
    "name": "Spicy Panko Prawn Nigiri",
    "description": "Spicy Panko Prawn Nigiri",
    "kJs": "473kJ",
    "Wheat": "YES",
    "Gluten": "YES",
    "Crustacea": "YES",
    "Mollusc": "",
    "Egg": "YES",
    "Milk": "",
    "Fish": "",
    "Peanut": "",
    "Soy": "YES",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "630",
    "category": "Deluxe",
    "name": "Creamy Salmon Sushi Nigiri",
    "description": "Creamy Salmon Sushi Nigiri",
    "kJs": "298kJ",
    "Wheat": "",
    "Gluten": "",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "YES",
    "Milk": "",
    "Fish": "YES",
    "Peanut": "",
    "Soy": "YES",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "637",
    "category": "Deluxe",
    "name": "Tempura Vegetable Nigiri",
    "description": "Tempura Vegetable Nigiri",
    "kJs": "260kJ",
    "Wheat": "YES",
    "Gluten": "YES",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "YES",
    "Milk": "",
    "Fish": "",
    "Peanut": "",
    "Soy": "YES",
    "Sesame": "",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "1052",
    "category": "Deluxe",
    "name": "Rainbow Uramaki",
    "description": "Rainbow Uramaki",
    "kJs": "448kJ",
    "Wheat": "",
    "Gluten": "",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "YES",
    "Milk": "YES",
    "Fish": "YES",
    "Peanut": "",
    "Soy": "YES",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "1301",
    "category": "Deluxe",
    "name": "Tamago Nigiri",
    "description": "Tamago Nigiri",
    "kJs": "210kJ",
    "Wheat": "",
    "Gluten": "",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "YES",
    "Milk": "YES",
    "Fish": "",
    "Peanut": "",
    "Soy": "",
    "Sesame": "",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "1302",
    "category": "Deluxe",
    "name": "Seared Unagi Nigiri",
    "description": "Seared Unagi Nigiri",
    "kJs": "214kJ",
    "Wheat": "YES",
    "Gluten": "YES",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "",
    "Milk": "",
    "Fish": "YES",
    "Peanut": "",
    "Soy": "YES",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "1305",
    "category": "Deluxe",
    "name": "Cooked Tuna Nigiri",
    "description": "Cooked Tuna Nigiri",
    "kJs": "991kJ",
    "Wheat": "",
    "Gluten": "",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "YES",
    "Milk": "",
    "Fish": "YES",
    "Peanut": "",
    "Soy": "YES",
    "Sesame": "",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "1306",
    "category": "Deluxe",
    "name": "Salmon Avocado Nigiri",
    "description": "Salmon Avocado Nigiri",
    "kJs": "248kJ",
    "Wheat": "",
    "Gluten": "",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "",
    "Milk": "",
    "Fish": "YES",
    "Peanut": "",
    "Soy": "",
    "Sesame": "",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "1308",
    "category": "Deluxe",
    "name": "Panko Prawn Nigiri",
    "description": "Panko Prawn Nigiri",
    "kJs": "474kJ",
    "Wheat": "YES",
    "Gluten": "YES",
    "Crustacea": "YES",
    "Mollusc": "",
    "Egg": "YES",
    "Milk": "",
    "Fish": "",
    "Peanut": "",
    "Soy": "YES",
    "Sesame": "",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "1309",
    "category": "Deluxe",
    "name": "Seared Scallop Nigiri",
    "description": "Seared Scallop Nigiri",
    "kJs": "225kJ",
    "Wheat": "",
    "Gluten": "",
    "Crustacea": "",
    "Mollusc": "YES",
    "Egg": "",
    "Milk": "",
    "Fish": "",
    "Peanut": "",
    "Soy": "YES",
    "Sesame": "",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "1400",
    "category": "Deluxe",
    "name": "Seared Salmon Nigiri",
    "description": "Seared Salmon Nigiri",
    "kJs": "299kJ",
    "Wheat": "",
    "Gluten": "",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "",
    "Milk": "",
    "Fish": "YES",
    "Peanut": "",
    "Soy": "YES",
    "Sesame": "",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "15538",
    "category": "Deluxe",
    "name": "Truffle Beef Nigiri",
    "description": "Truffle Beef Nigiri",
    "kJs": "250kJ",
    "Wheat": "",
    "Gluten": "",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "YES",
    "Milk": "",
    "Fish": "",
    "Peanut": "",
    "Soy": "",
    "Sesame": "",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "16001",
    "category": "Deluxe",
    "name": "Tempura Vegetable Pancake",
    "description": "Tempura Vegetable Pancake",
    "kJs": "1590kJ",
    "Wheat": "YES",
    "Gluten": "YES",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "YES",
    "Milk": "YES",
    "Fish": "",
    "Peanut": "",
    "Soy": "YES",
    "Sesame": "",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "16002",
    "category": "Deluxe",
    "name": "Teriyaki Chicken & Edamame Loaded Pancake",
    "description": "Teriyaki Chicken & Edamame Loaded Pancake",
    "kJs": "1970kJ",
    "Wheat": "YES",
    "Gluten": "YES",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "YES",
    "Milk": "YES",
    "Fish": "",
    "Peanut": "",
    "Soy": "YES",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "16003",
    "category": "Deluxe",
    "name": "Salmon & Avocado Loaded Pancake",
    "description": "Salmon & Avocado Loaded Pancake",
    "kJs": "2160kJ",
    "Wheat": "YES",
    "Gluten": "YES",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "YES",
    "Milk": "YES",
    "Fish": "YES",
    "Peanut": "",
    "Soy": "YES",
    "Sesame": "",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "89904",
    "category": "Deluxe",
    "name": "Spicy Rainbow Uramaki",
    "description": "Spicy Rainbow Uramaki",
    "kJs": "405kJ",
    "Wheat": "",
    "Gluten": "",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "YES",
    "Milk": "YES",
    "Fish": "YES",
    "Peanut": "",
    "Soy": "YES",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "89907",
    "category": "Deluxe",
    "name": "Tiger Uramaki",
    "description": "Tiger Uramaki",
    "kJs": "365kJ",
    "Wheat": "YES",
    "Gluten": "YES",
    "Crustacea": "YES",
    "Mollusc": "",
    "Egg": "YES",
    "Milk": "YES",
    "Fish": "YES",
    "Peanut": "",
    "Soy": "YES",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "880425",
    "category": "Deluxe",
    "name": "Spicy Fresh Tuna Nigiri ",
    "description": "Spicy Fresh Tuna Nigiri ",
    "kJs": "224kJ",
    "Wheat": "",
    "Gluten": "",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "YES",
    "Milk": "",
    "Fish": "YES",
    "Peanut": "",
    "Soy": "",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "880427",
    "category": "Deluxe",
    "name": "King Fish Nigiri",
    "description": "",
    "kJs": "217kJ",
    "Wheat": "",
    "Gluten": "",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "",
    "Milk": "",
    "Fish": "YES",
    "Peanut": "",
    "Soy": "",
    "Sesame": "",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "15",
    "category": "Pack",
    "name": "Prawn Sushi Pack",
    "description": "Prawn Sushi Pack",
    "kJs": "1170kJ",
    "Wheat": "",
    "Gluten": "",
    "Crustacea": "YES",
    "Mollusc": "",
    "Egg": "",
    "Milk": "",
    "Fish": "",
    "Peanut": "",
    "Soy": "YES",
    "Sesame": "",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "151",
    "category": "Pack",
    "name": "Spicy Crunchy Cooked Tuna Pack",
    "description": "Spicy Crunchy Cooked Tuna Pack",
    "kJs": "2390kJ",
    "Wheat": "",
    "Gluten": "",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "YES",
    "Milk": "",
    "Fish": "YES",
    "Peanut": "",
    "Soy": "YES",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "152",
    "category": "Pack",
    "name": "Vegetarian Pack",
    "description": "Vegetarian Pack",
    "kJs": "1310kJ",
    "Wheat": "",
    "Gluten": "",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "YES",
    "Milk": "YES",
    "Fish": "",
    "Peanut": "",
    "Soy": "YES",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "155",
    "category": "Pack",
    "name": "Crispy Chicken and Salt & Pepper Squid Pack",
    "description": "Crispy Chicken and Salt & Pepper Squid Pack",
    "kJs": "2260kJ",
    "Wheat": "YES",
    "Gluten": "YES",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "YES",
    "Milk": "",
    "Fish": "YES",
    "Peanut": "",
    "Soy": "YES",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "156",
    "category": "Pack",
    "name": "Prawn Combo Pack",
    "description": "Prawn Combo Pack",
    "kJs": "2240kJ",
    "Wheat": "YES",
    "Gluten": "YES",
    "Crustacea": "YES",
    "Mollusc": "",
    "Egg": "YES",
    "Milk": "YES",
    "Fish": "YES",
    "Peanut": "",
    "Soy": "YES",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "301",
    "category": "Pack",
    "name": "California Roll Pack",
    "description": "California Roll Pack",
    "kJs": "1760kJ",
    "Wheat": "YES",
    "Gluten": "YES",
    "Crustacea": "YES",
    "Mollusc": "",
    "Egg": "YES",
    "Milk": "YES",
    "Fish": "YES",
    "Peanut": "",
    "Soy": "YES",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "303",
    "category": "Pack",
    "name": "Salmon & Tuna Nigiri Pack",
    "description": "Salmon & Tuna Nigiri Pack",
    "kJs": "1700kJ",
    "Wheat": "",
    "Gluten": "",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "",
    "Milk": "",
    "Fish": "YES",
    "Peanut": "",
    "Soy": "YES",
    "Sesame": "",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "304",
    "category": "Pack",
    "name": "Assorted Sushi Pack",
    "description": "Assorted Sushi Pack",
    "kJs": "1890kJ",
    "Wheat": "YES",
    "Gluten": "YES",
    "Crustacea": "YES",
    "Mollusc": "",
    "Egg": "YES",
    "Milk": "YES",
    "Fish": "YES",
    "Peanut": "",
    "Soy": "YES",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "305",
    "category": "Pack",
    "name": "Salmon Sashimi Pack Large",
    "description": "Salmon Sashimi Pack Large",
    "kJs": "1410kJ",
    "Wheat": "",
    "Gluten": "",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "",
    "Milk": "",
    "Fish": "YES",
    "Peanut": "",
    "Soy": "YES",
    "Sesame": "",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "306",
    "category": "Pack",
    "name": "Sushi Sashimi Deluxe Pack",
    "description": "Sushi Sashimi Deluxe Pack",
    "kJs": "2830kJ",
    "Wheat": "YES",
    "Gluten": "YES",
    "Crustacea": "YES",
    "Mollusc": "",
    "Egg": "YES",
    "Milk": "YES",
    "Fish": "YES",
    "Peanut": "",
    "Soy": "YES",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "307",
    "category": "Pack",
    "name": "Sushi Deluxe Pack",
    "description": "Sushi Deluxe Pack",
    "kJs": "2620kJ",
    "Wheat": "YES",
    "Gluten": "YES",
    "Crustacea": "YES",
    "Mollusc": "",
    "Egg": "YES",
    "Milk": "YES",
    "Fish": "YES",
    "Peanut": "",
    "Soy": "YES",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "308",
    "category": "Pack",
    "name": "Maki Pack",
    "description": "Maki Pack",
    "kJs": "1610kJ",
    "Wheat": "",
    "Gluten": "",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "",
    "Milk": "",
    "Fish": "YES",
    "Peanut": "",
    "Soy": "YES",
    "Sesame": "",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "310",
    "category": "Pack",
    "name": "Bento Box",
    "description": "Bento Box",
    "kJs": "2900kJ",
    "Wheat": "YES",
    "Gluten": "YES",
    "Crustacea": "YES",
    "Mollusc": "",
    "Egg": "YES",
    "Milk": "YES",
    "Fish": "YES",
    "Peanut": "",
    "Soy": "YES",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "311",
    "category": "Pack",
    "name": "Tobiko Pack",
    "description": "Tobiko Pack",
    "kJs": "2380kJ",
    "Wheat": "",
    "Gluten": "",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "YES",
    "Milk": "",
    "Fish": "YES",
    "Peanut": "",
    "Soy": "YES",
    "Sesame": "",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "314",
    "category": "Pack",
    "name": "Salmon Tuna Sashimi Pack",
    "description": "Salmon Tuna Sashimi Pack",
    "kJs": "1410kJ",
    "Wheat": "",
    "Gluten": "",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "",
    "Milk": "",
    "Fish": "YES",
    "Peanut": "",
    "Soy": "YES",
    "Sesame": "",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "321",
    "category": "Pack",
    "name": "Prawn & California Roll Pack",
    "description": "Prawn & California Roll Pack",
    "kJs": "1460kJ",
    "Wheat": "YES",
    "Gluten": "YES",
    "Crustacea": "YES",
    "Mollusc": "",
    "Egg": "YES",
    "Milk": "YES",
    "Fish": "YES",
    "Peanut": "",
    "Soy": "YES",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "612310",
    "category": "Pack",
    "name": "Seafood Lovers Mini Pack",
    "description": "",
    "kJs": "1160kJ",
    "Wheat": "YES",
    "Gluten": "YES",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "YES",
    "Milk": "",
    "Fish": "YES",
    "Peanut": "",
    "Soy": "YES",
    "Sesame": "",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "612311",
    "category": "Pack",
    "name": "Chicken & Vegetarian Uramaki Mini Pack",
    "description": "",
    "kJs": "824kJ",
    "Wheat": "YES",
    "Gluten": "YES",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "YES",
    "Milk": "",
    "Fish": "",
    "Peanut": "",
    "Soy": "YES",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "612312",
    "category": "Pack",
    "name": "Assorted Hand Roll Mini Pack",
    "description": "",
    "kJs": "2250kJ",
    "Wheat": "YES",
    "Gluten": "YES",
    "Crustacea": "YES",
    "Mollusc": "",
    "Egg": "YES",
    "Milk": "",
    "Fish": "YES",
    "Peanut": "",
    "Soy": "YES",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "612313",
    "category": "Pack",
    "name": "Nigiri & Inari Mini Pack",
    "description": "",
    "kJs": "871kJ",
    "Wheat": "",
    "Gluten": "",
    "Crustacea": "YES",
    "Mollusc": "",
    "Egg": "YES",
    "Milk": "YES",
    "Fish": "YES",
    "Peanut": "",
    "Soy": "YES",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "612314",
    "category": "Pack",
    "name": "Vegan Mini Pack",
    "description": "",
    "kJs": "955kJ",
    "Wheat": "",
    "Gluten": "",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "",
    "Milk": "",
    "Fish": "",
    "Peanut": "",
    "Soy": "YES",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "612315",
    "category": "Pack",
    "name": "Sashimi Mini Pack",
    "description": "",
    "kJs": "465kJ",
    "Wheat": "",
    "Gluten": "",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "",
    "Milk": "",
    "Fish": "YES",
    "Peanut": "",
    "Soy": "YES",
    "Sesame": "",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "612316",
    "category": "Pack",
    "name": "Kids Pack with Veggies",
    "description": "",
    "kJs": "701kJ",
    "Wheat": "",
    "Gluten": "",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "YES",
    "Milk": "",
    "Fish": "YES",
    "Peanut": "",
    "Soy": "YES",
    "Sesame": "",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "612317",
    "category": "Pack",
    "name": "Kids Pack with Cookies",
    "description": "",
    "kJs": "1210kJ",
    "Wheat": "YES",
    "Gluten": "YES",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "YES",
    "Milk": "YES",
    "Fish": "YES",
    "Peanut": "",
    "Soy": "YES",
    "Sesame": "",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "831136",
    "category": "Pack",
    "name": "Futomaki Pack",
    "description": "",
    "kJs": "1310kJ",
    "Wheat": "",
    "Gluten": "",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "YES",
    "Milk": "YES",
    "Fish": "",
    "Peanut": "",
    "Soy": "YES",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "515",
    "category": "Pack",
    "name": "Salmon Nigiri Pack",
    "description": "Salmon Nigiri Pack",
    "kJs": "1960kJ",
    "Wheat": "",
    "Gluten": "",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "",
    "Milk": "",
    "Fish": "YES",
    "Peanut": "",
    "Soy": "YES",
    "Sesame": "",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "556",
    "category": "Pack",
    "name": "Crispy Chicken Pack ",
    "description": "Crispy Chicken Pack ",
    "kJs": "1410kJ",
    "Wheat": "YES",
    "Gluten": "YES",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "YES",
    "Milk": "",
    "Fish": "",
    "Peanut": "",
    "Soy": "YES",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "15641",
    "category": "Pack",
    "name": "Trifecta Pack ",
    "description": "Trifecta Pack ",
    "kJs": "2190kJ",
    "Wheat": "",
    "Gluten": "",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "YES",
    "Milk": "",
    "Fish": "YES",
    "Peanut": "",
    "Soy": "YES",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "831136",
    "category": "Pack",
    "name": "Futomaki Pack",
    "description": "",
    "kJs": "1310kJ",
    "Wheat": "",
    "Gluten": "",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "YES",
    "Milk": "YES",
    "Fish": "",
    "Peanut": "",
    "Soy": "YES",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "605",
    "category": "Hot Food",
    "name": "Katsu Chicken Bento",
    "description": "",
    "kJs": "",
    "Wheat": "",
    "Gluten": "",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "",
    "Milk": "",
    "Fish": "",
    "Peanut": "",
    "Soy": "",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "1228",
    "category": "Hot Food",
    "name": "Teriyaki Chicken Bento",
    "description": "",
    "kJs": "",
    "Wheat": "",
    "Gluten": "",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "",
    "Milk": "",
    "Fish": "",
    "Peanut": "",
    "Soy": "",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "603",
    "category": "Hot Food",
    "name": "Teriyaki Salmon Bento",
    "description": "",
    "kJs": "",
    "Wheat": "",
    "Gluten": "",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "",
    "Milk": "",
    "Fish": "",
    "Peanut": "",
    "Soy": "",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "1231",
    "category": "Hot Food",
    "name": "Tempura Prawn Bento",
    "description": "",
    "kJs": "",
    "Wheat": "",
    "Gluten": "",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "",
    "Milk": "",
    "Fish": "",
    "Peanut": "",
    "Soy": "",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "53",
    "category": "Hot Food",
    "name": "Unagi Bento",
    "description": "",
    "kJs": "",
    "Wheat": "",
    "Gluten": "",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "",
    "Milk": "",
    "Fish": "",
    "Peanut": "",
    "Soy": "",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "1229",
    "category": "Hot Food",
    "name": "Katsu Chicken Curry Don",
    "description": "",
    "kJs": "",
    "Wheat": "",
    "Gluten": "",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "",
    "Milk": "",
    "Fish": "",
    "Peanut": "",
    "Soy": "",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "433",
    "category": "Hot Food",
    "name": "Teriyaki Chicken Don",
    "description": "",
    "kJs": "",
    "Wheat": "",
    "Gluten": "",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "",
    "Milk": "",
    "Fish": "",
    "Peanut": "",
    "Soy": "",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "57",
    "category": "Hot Food",
    "name": "Unagi Don",
    "description": "",
    "kJs": "",
    "Wheat": "",
    "Gluten": "",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "",
    "Milk": "",
    "Fish": "",
    "Peanut": "",
    "Soy": "",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "639",
    "category": "Hot Food",
    "name": "Teriyaki Salmon Don",
    "description": "",
    "kJs": "",
    "Wheat": "",
    "Gluten": "",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "",
    "Milk": "",
    "Fish": "",
    "Peanut": "",
    "Soy": "",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "443",
    "category": "Hot Food",
    "name": "Teriyaki Chicken Udon",
    "description": "",
    "kJs": "",
    "Wheat": "",
    "Gluten": "",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "",
    "Milk": "",
    "Fish": "",
    "Peanut": "",
    "Soy": "",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "444",
    "category": "Hot Food",
    "name": "Tempura Prawn Udon",
    "description": "",
    "kJs": "",
    "Wheat": "",
    "Gluten": "",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "",
    "Milk": "",
    "Fish": "",
    "Peanut": "",
    "Soy": "",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "442",
    "category": "Hot Food",
    "name": "Vegetarian Udon",
    "description": "",
    "kJs": "502kJ",
    "Wheat": "",
    "Gluten": "",
    "Crustacea": "",
    "Mollusc": "YES",
    "Egg": "",
    "Milk": "",
    "Fish": "YES",
    "Peanut": "",
    "Soy": "YES",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "15642",
    "category": "Pack",
    "name": "Favourites Pack ",
    "description": "Favourites Pack ",
    "kJs": "1440kJ",
    "Wheat": "",
    "Gluten": "",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "YES",
    "Milk": "",
    "Fish": "YES",
    "Peanut": "",
    "Soy": "YES",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "89903",
    "category": "Pack",
    "name": "Mixed Sashimi Pack",
    "description": "Mixed Sashimi Pack",
    "kJs": "1080kJ",
    "Wheat": "",
    "Gluten": "",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "",
    "Milk": "",
    "Fish": "YES",
    "Peanut": "",
    "Soy": "YES",
    "Sesame": "",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "880415",
    "category": "Pack",
    "name": "Salmon Sashimi Pack Small ",
    "description": "Salmon Sashimi Pack Small ",
    "kJs": "964kJ",
    "Wheat": "",
    "Gluten": "",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "",
    "Milk": "",
    "Fish": "YES",
    "Peanut": "",
    "Soy": "YES",
    "Sesame": "",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "880423",
    "category": "Salads",
    "name": "Salmon Poke Bowl ",
    "description": "Salmon Poke Bowl ",
    "kJs": "1790kJ",
    "Wheat": "",
    "Gluten": "",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "",
    "Milk": "",
    "Fish": "YES",
    "Peanut": "",
    "Soy": "YES",
    "Sesame": "",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "880438",
    "category": "Salads",
    "name": "Fresh Tuna Poke Bowl ",
    "description": "Fresh Tuna Poke Bowl ",
    "kJs": "1780kJ",
    "Wheat": "",
    "Gluten": "",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "",
    "Milk": "",
    "Fish": "YES",
    "Peanut": "",
    "Soy": "YES",
    "Sesame": "",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "880440",
    "category": "Salads",
    "name": "Karaage Chicken Poke Bowl ",
    "description": "Karaage Chicken Poke Bowl ",
    "kJs": "2160kJ",
    "Wheat": "YES",
    "Gluten": "YES",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "",
    "Milk": "",
    "Fish": "YES",
    "Peanut": "",
    "Soy": "YES",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "880442",
    "category": "Salads",
    "name": "Vegetarian Poke Bowl ",
    "description": "Vegetarian Poke Bowl ",
    "kJs": "1760kJ",
    "Wheat": "",
    "Gluten": "",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "YES",
    "Milk": "YES",
    "Fish": "",
    "Peanut": "",
    "Soy": "YES",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "501",
    "category": "Salads",
    "name": "Pickled Squid Salad",
    "description": "Pickled Squid Salad",
    "kJs": "502kJ",
    "Wheat": "YES",
    "Gluten": "YES",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "",
    "Milk": "",
    "Fish": "YES",
    "Peanut": "",
    "Soy": "YES",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "502",
    "category": "Salads",
    "name": "Seaweed Salad",
    "description": "Seaweed Salad",
    "kJs": "519kJ",
    "Wheat": "YES",
    "Gluten": "YES",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "",
    "Milk": "",
    "Fish": "",
    "Peanut": "",
    "Soy": "YES",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "504",
    "category": "Salads",
    "name": "Seafood Salad",
    "description": "Seafood Salad",
    "kJs": "1740kJ",
    "Wheat": "YES",
    "Gluten": "YES",
    "Crustacea": "YES",
    "Mollusc": "",
    "Egg": "YES",
    "Milk": "",
    "Fish": "YES",
    "Peanut": "",
    "Soy": "YES",
    "Sesame": "",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "505",
    "category": "Salads",
    "name": "Beef Tataki",
    "description": "Beef Tataki",
    "kJs": "977kJ",
    "Wheat": "YES",
    "Gluten": "YES",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "",
    "Milk": "",
    "Fish": "",
    "Peanut": "",
    "Soy": "YES",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "1044",
    "category": "Salads",
    "name": "Salted Edamame",
    "description": "Salted Edamame",
    "kJs": "612kJ",
    "Wheat": "",
    "Gluten": "",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "",
    "Milk": "",
    "Fish": "",
    "Peanut": "",
    "Soy": "YES",
    "Sesame": "",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "831095",
    "category": "Sliders & Sandwiches",
    "name": "Tempura Salmon & Avocado Sushi Sandwich",
    "description": "Tempura Salmon & Avocado Sushi Sandwich",
    "kJs": "877kJ",
    "Wheat": "YES",
    "Gluten": "YES",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "YES",
    "Milk": "",
    "Fish": "YES",
    "Peanut": "",
    "Soy": "YES",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "831096",
    "category": "Sliders & Sandwiches",
    "name": "Crispy Chicken Sushi Sandwich",
    "description": "Crispy Chicken Sushi Sandwich",
    "kJs": "987kJ",
    "Wheat": "YES",
    "Gluten": "YES",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "YES",
    "Milk": "",
    "Fish": "",
    "Peanut": "",
    "Soy": "YES",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "831103",
    "category": "Sliders & Sandwiches",
    "name": "Crispy Chicken Slider",
    "description": "Crispy Chicken Slider",
    "kJs": "1200kJ",
    "Wheat": "YES",
    "Gluten": "YES",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "YES",
    "Milk": "YES",
    "Fish": "",
    "Peanut": "",
    "Soy": "YES",
    "Sesame": "",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "831104",
    "category": "Sliders & Sandwiches",
    "name": "Spicy Popcorn Prawn Slider",
    "description": "Spicy Popcorn Prawn Slider",
    "kJs": "1300kJ",
    "Wheat": "YES",
    "Gluten": "YES",
    "Crustacea": "YES",
    "Mollusc": "",
    "Egg": "YES",
    "Milk": "YES",
    "Fish": "",
    "Peanut": "",
    "Soy": "",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "21",
    "category": "White Rice",
    "name": "Peking Duck",
    "description": "Peking Duck",
    "kJs": "665kJ",
    "Wheat": "YES",
    "Gluten": "YES",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "",
    "Milk": "",
    "Fish": "",
    "Peanut": "",
    "Soy": "YES",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "101",
    "category": "White Rice",
    "name": "Teriyaki Chicken ",
    "description": "Teriyaki Chicken ",
    "kJs": "637kJ",
    "Wheat": "",
    "Gluten": "",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "",
    "Milk": "",
    "Fish": "",
    "Peanut": "",
    "Soy": "YES",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "102",
    "category": "White Rice",
    "name": "Cooked Tuna & Avocado ",
    "description": "Cooked Tuna & Avocado ",
    "kJs": "711kJ",
    "Wheat": "",
    "Gluten": "",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "YES",
    "Milk": "",
    "Fish": "YES",
    "Peanut": "",
    "Soy": "YES",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "103",
    "category": "White Rice",
    "name": "Crispy Chicken",
    "description": "Crispy Chicken",
    "kJs": "790kJ",
    "Wheat": "YES",
    "Gluten": "YES",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "YES",
    "Milk": "",
    "Fish": "",
    "Peanut": "",
    "Soy": "YES",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "104",
    "category": "White Rice",
    "name": "Smoked Salmon & Avocado ",
    "description": "Smoked Salmon & Avocado ",
    "kJs": "769kJ",
    "Wheat": "",
    "Gluten": "",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "YES",
    "Milk": "",
    "Fish": "YES",
    "Peanut": "",
    "Soy": "",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "105",
    "category": "White Rice",
    "name": "Salmon & Avocado ",
    "description": "Salmon & Avocado ",
    "kJs": "808kJ",
    "Wheat": "",
    "Gluten": "",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "YES",
    "Milk": "",
    "Fish": "YES",
    "Peanut": "",
    "Soy": "",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "116",
    "category": "White Rice",
    "name": "Tamago & Cucumber ",
    "description": "",
    "kJs": "564kJ",
    "Wheat": "",
    "Gluten": "",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "YES",
    "Milk": "YES",
    "Fish": "",
    "Peanut": "",
    "Soy": "",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "106",
    "category": "White Rice",
    "name": "Tobiko & Avocado",
    "description": "Tobiko & Avocado",
    "kJs": "698kJ",
    "Wheat": "",
    "Gluten": "",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "YES",
    "Milk": "",
    "Fish": "YES",
    "Peanut": "",
    "Soy": "YES",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "107",
    "category": "White Rice",
    "name": "Prawn & Avocado",
    "description": "Prawn & Avocado",
    "kJs": "659kJ",
    "Wheat": "",
    "Gluten": "",
    "Crustacea": "YES",
    "Mollusc": "",
    "Egg": "YES",
    "Milk": "",
    "Fish": "",
    "Peanut": "",
    "Soy": "",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "108",
    "category": "White Rice",
    "name": "California ",
    "description": "California ",
    "kJs": "728kJ",
    "Wheat": "YES",
    "Gluten": "YES",
    "Crustacea": "YES",
    "Mollusc": "",
    "Egg": "YES",
    "Milk": "",
    "Fish": "YES",
    "Peanut": "",
    "Soy": "YES",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "109",
    "category": "White Rice",
    "name": "Fresh Tuna & Cucumber ",
    "description": "Fresh Tuna & Cucumber ",
    "kJs": "647kJ",
    "Wheat": "",
    "Gluten": "",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "YES",
    "Milk": "",
    "Fish": "YES",
    "Peanut": "",
    "Soy": "",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "110",
    "category": "White Rice",
    "name": "Spicy Cooked Tuna & Cucumber ",
    "description": "Spicy Cooked Tuna & Cucumber ",
    "kJs": "743kJ",
    "Wheat": "",
    "Gluten": "",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "YES",
    "Milk": "",
    "Fish": "YES",
    "Peanut": "",
    "Soy": "YES",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "113",
    "category": "White Rice",
    "name": "Panko Prawn ",
    "description": "Panko Prawn ",
    "kJs": "902kJ",
    "Wheat": "YES",
    "Gluten": "YES",
    "Crustacea": "YES",
    "Mollusc": "",
    "Egg": "YES",
    "Milk": "",
    "Fish": "YES",
    "Peanut": "",
    "Soy": "YES",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "114",
    "category": "White Rice",
    "name": "Tempura Salmon",
    "description": "Tempura Salmon",
    "kJs": "951kJ",
    "Wheat": "YES",
    "Gluten": "",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "YES",
    "Milk": "",
    "Fish": "YES",
    "Peanut": "",
    "Soy": "YES",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "144",
    "category": "White Rice",
    "name": "Cooked Tuna & Corn ",
    "description": "Cooked Tuna & Corn ",
    "kJs": "621kJ",
    "Wheat": "",
    "Gluten": "",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "YES",
    "Milk": "",
    "Fish": "YES",
    "Peanut": "",
    "Soy": "YES",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "201",
    "category": "White Rice",
    "name": "Vegetarian ",
    "description": "Vegetarian ",
    "kJs": "564kJ",
    "Wheat": "",
    "Gluten": "",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "",
    "Milk": "",
    "Fish": "",
    "Peanut": "",
    "Soy": "YES",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "YES",
    "Lupin": ""
  },
  {
    "id": "202",
    "category": "White Rice",
    "name": "Cucumber & Avocado ",
    "description": "Cucumber & Avocado ",
    "kJs": "564kJ",
    "Wheat": "",
    "Gluten": "",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "",
    "Milk": "",
    "Fish": "",
    "Peanut": "",
    "Soy": "",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "207",
    "category": "White Rice",
    "name": "Special California ",
    "description": "Special California ",
    "kJs": "675kJ",
    "Wheat": "YES",
    "Gluten": "YES",
    "Crustacea": "YES",
    "Mollusc": "",
    "Egg": "YES",
    "Milk": "",
    "Fish": "YES",
    "Peanut": "",
    "Soy": "YES",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "209",
    "category": "White Rice",
    "name": "Soft Shell Crab",
    "description": "Soft Shell Crab",
    "kJs": "866kJ",
    "Wheat": "YES",
    "Gluten": "YES",
    "Crustacea": "YES",
    "Mollusc": "",
    "Egg": "YES",
    "Milk": "",
    "Fish": "",
    "Peanut": "",
    "Soy": "YES",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "YES",
    "Lupin": ""
  },
  {
    "id": "211",
    "category": "White Rice",
    "name": "Avocado ",
    "description": "Avocado ",
    "kJs": "603kJ",
    "Wheat": "",
    "Gluten": "",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "",
    "Milk": "",
    "Fish": "",
    "Peanut": "",
    "Soy": "",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "248",
    "category": "White Rice",
    "name": "Tofu & Cucumber ",
    "description": "Tofu & Cucumber ",
    "kJs": "622kJ",
    "Wheat": "",
    "Gluten": "",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "",
    "Milk": "",
    "Fish": "",
    "Peanut": "",
    "Soy": "YES",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "374",
    "category": "White Rice",
    "name": "Spicy Prawn & Cucumber",
    "description": "Spicy Prawn & Cucumber",
    "kJs": "616kJ",
    "Wheat": "",
    "Gluten": "",
    "Crustacea": "YES",
    "Mollusc": "",
    "Egg": "YES",
    "Milk": "",
    "Fish": "",
    "Peanut": "",
    "Soy": "",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "426",
    "category": "White Rice",
    "name": "Spicy Salmon & Cucumber ",
    "description": "Spicy Salmon & Cucumber ",
    "kJs": "749kJ",
    "Wheat": "",
    "Gluten": "",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "YES",
    "Milk": "",
    "Fish": "YES",
    "Peanut": "",
    "Soy": "YES",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "541",
    "category": "White Rice",
    "name": "Cooked Tuna & Cucumber ",
    "description": "Cooked Tuna & Cucumber ",
    "kJs": "649kJ",
    "Wheat": "",
    "Gluten": "",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "YES",
    "Milk": "",
    "Fish": "YES",
    "Peanut": "",
    "Soy": "YES",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "559",
    "category": "White Rice",
    "name": "Spicy Fresh Tuna & Cucumber",
    "description": "Spicy Fresh Tuna & Cucumber",
    "kJs": "644kJ",
    "Wheat": "",
    "Gluten": "",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "YES",
    "Milk": "",
    "Fish": "YES",
    "Peanut": "",
    "Soy": "",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "565",
    "category": "White Rice",
    "name": "Spicy Crispy Chicken",
    "description": "Spicy Crispy Chicken",
    "kJs": "787kJ",
    "Wheat": "YES",
    "Gluten": "YES",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "YES",
    "Milk": "",
    "Fish": "",
    "Peanut": "",
    "Soy": "YES",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "580",
    "category": "White Rice",
    "name": "Salt & Pepper Squid ",
    "description": "Salt & Pepper Squid ",
    "kJs": "814kJ",
    "Wheat": "YES",
    "Gluten": "YES",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "YES",
    "Milk": "",
    "Fish": "YES",
    "Peanut": "",
    "Soy": "",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "15530",
    "category": "White Rice",
    "name": "Crispy not Chicken",
    "description": "Crispy not Chicken",
    "kJs": "792kJ",
    "Wheat": "YES",
    "Gluten": "",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "",
    "Milk": "",
    "Fish": "",
    "Peanut": "",
    "Soy": "YES",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "15625",
    "category": "White Rice",
    "name": "Pork Katsu ",
    "description": "Pork Katsu ",
    "kJs": "783kJ",
    "Wheat": "YES",
    "Gluten": "YES",
    "Crustacea": "YES",
    "Mollusc": "",
    "Egg": "YES",
    "Milk": "YES",
    "Fish": "YES",
    "Peanut": "",
    "Soy": "YES",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "15650",
    "category": "White Rice",
    "name": "Truffle Beef",
    "description": "Truffle Beef",
    "kJs": "983kJ",
    "Wheat": "",
    "Gluten": "",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "YES",
    "Milk": "",
    "Fish": "",
    "Peanut": "",
    "Soy": "",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "831218",
    "category": "White Rice",
    "name": "Tempura Vegetable ",
    "description": "Tempura Vegetable ",
    "kJs": "1040kJ",
    "Wheat": "YES",
    "Gluten": "YES",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "YES",
    "Milk": "YES",
    "Fish": "",
    "Peanut": "",
    "Soy": "YES",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  },
  {
    "id": "831276",
    "category": "White Rice",
    "name": "Spicy Crunchy Cooked Tuna   ",
    "description": "Spicy Crunchy Cooked Tuna   ",
    "kJs": "835kJ",
    "Wheat": "",
    "Gluten": "",
    "Crustacea": "",
    "Mollusc": "",
    "Egg": "YES",
    "Milk": "",
    "Fish": "YES",
    "Peanut": "",
    "Soy": "YES",
    "Sesame": "YES",
    "Tree Nuts": "",
    "Sulphites": "",
    "Lupin": ""
  }
];

export default Data;